--truncate table SEED.UACCENTRYD
CREATE SEQUENCE SEED.ZSEQ START WITH 1 INCREMENT BY 1

SET NOCOUNT ON

TRUNCATE TABLE SEED.ZACCENTRYD
ALTER SEQUENCE SEED.ZSEQ RESTART WITH 1

ALTER TABLE SEED.ZACCENTRYD ADD StartTime DATETIME2 NOT NULL , EndTime DATETIME2 NOT NULL
UPDATE SEED.ZACCENTRYD SET StartTime = '19000101 00:00:00.0000000', EndTime = '99991231 23:59:59.9999999'
ALTER TABLE SEED.ZACCENTRYD ADD PERIOD FOR SYSTEM_TIME(StartTime, EndTime)
ALTER TABLE SEED.ZACCENTRYD SET (SYSTEM_VERSIONING = ON(HISTORY_TABLE = SEED.ZACCENTRYD_HISTORY, DATA_CONSISTENCY_CHECK = ON))


DECLARE @i integer, @startTime DATETIME2, @endTime DATETIME2
SET @startTime = CURRENT_TIMESTAMP
SET @i = 1
WHILE @i < 20000
BEGIN
	ALTER SEQUENCE SEED.ZSEQ RESTART WITH 1
	INSERT INTO SEED.ZACCENTRYD(UPDTICK_0, TYP_0, NUM_0, LIN_0, LEDTYP_0, LED_0, ACCNUM_0, CHRNUM_0, IDTLIN_0, CPY_0, FCYLIN_0, ACCDAT_0, FIY_0, PER_0, COA_0, SAC_0, ACC_0, BPR_0, DSP_0, SNS_0, CUR_0, AMTCUR_0, 
							 CURLED_0, AMTLED_0, AMTFLG_0, AMTLED1_0, UOM_0, QTY_0, DES_0, REFINTLIN_0, OFFACC_0, CSLCOD_0, CSLFLO_0, STT1_0, STT2_0, STT3_0, MTC_0, MTCDAT_0, MTCDATMIN_0, MTCDATMAX_0, 
							 FLGMTC_0, FREREF_0, CHK_0, CHKDAT_0, MRK_0, TAX_0, TAX2_0, TAX3_0, AMTVAT_0, INDEDVAT_0, EXPNUM_0, ACCNUMORI_0, ACCNUMDOE_0, CAPFLOTYP_0, VATRAT_0, VATDEDRAT_0, CREDATTIM_0, 
							 UPDDATTIM_0, AUUID_0, CREUSR_0, UPDUSR_0, CSLBPR_0, PJTLIN_0)
	SELECT        UPDTICK_0, 'ZBOB' TYP_0, 'ZNUMB' + cast(@i as nvarchar(10)) NUM_0, (NEXT VALUE FOR SEED.ZSEQ) LIN_0, LEDTYP_0, LED_0, ACCNUM_0, CHRNUM_0, IDTLIN_0, CPY_0, FCYLIN_0, ACCDAT_0, FIY_0, PER_0, COA_0, SAC_0, ACC_0, BPR_0, DSP_0, SNS_0, CUR_0, AMTCUR_0, 
							 CURLED_0, AMTLED_0, AMTFLG_0, AMTLED1_0, UOM_0, QTY_0, DES_0, REFINTLIN_0, OFFACC_0, CSLCOD_0, CSLFLO_0, STT1_0, STT2_0, STT3_0, MTC_0, MTCDAT_0, MTCDATMIN_0, MTCDATMAX_0, 
							 FLGMTC_0, FREREF_0, CHK_0, CHKDAT_0, MRK_0, TAX_0, TAX2_0, TAX3_0, AMTVAT_0, INDEDVAT_0, EXPNUM_0, ACCNUMORI_0, ACCNUMDOE_0, CAPFLOTYP_0, VATRAT_0, VATDEDRAT_0, CREDATTIM_0, 
							 UPDDATTIM_0, AUUID_0, CREUSR_0, UPDUSR_0, CSLBPR_0, PJTLIN_0
	--INTO #tmp
	FROM            SEED.GACCENTRYD d--, (select top 32000 * FROM sys.columns) c
	WHERE NUM_0 = 'NA0211303INV000066' AND LIN_0 = 10 AND LEDTYP_0 = 3 AND TYP_0 = 'CSINV'

	SET @i += 1
END

UPDATE SEED.ZACCENTRYD
SET CREUSR_0 = 'BOB'

SET @endTime = CURRENT_TIMESTAMP
SELECT DATEDIFF(SECOND, @startTime, @endTime)

CREATE NONCLUSTERED INDEX idxSortFix ON SEED.UACCENTRYD(NUM_0 ASC, TYP_0 ASC, LEDTYP_0 ASC) 

ALTER TABLE SEED.ZACCENTRYD ADD StartTime DATETIME2, EndTime DATETIME2
UPDATE SEED.ZACCENTRYD SET StartTime = '19000101 00:00:00.0000000', EndTime = '99991231 23:59:59.9999999'
ALTER TABLE SEED.ZACCENTRYD ALTER COLUMN StartTime DATETIME2 NOT NULL
ALTER TABLE SEED.ZACCENTRYD ALTER COLUMN EndTime DATETIME2 NOT NULL
select top 10 * from SEED.ZACCENTRYD
select top 10 * from SEED.ZACCENTRYD_HISTORY

